Repository fedora-sysv/chkconfig, pull requests merged in 2021-07, with the labels that each got.

#57 alternatives: add --keep-foreign
  alternatives.8
  alternatives.c
Labels: new-feature

#58 alternatives: tweak manpage to match the real 'remove' behavior
  alternatives.8
Labels: enhancement

#59 spec: /sbin/chkconfig -> /usr/sbin/chkconfig
  Makefile
  chkconfig.spec
Labels: bugfix, enhancement

#60 Add Provides /sbin/chkconfig in order to stay backwards compatible
  chkconfig.spec
Labels: enhancement

#61 spec: Revert changes introduced in Fedora
  chkconfig.spec
Labels: RHEL8, enhancement

#62 spec: Replace not working awk command with sed
  Makefile
Labels: enhancement

#63 spec: Replace not working awk command with sed
  Makefile
Labels: RHEL8, enhancement
