Repository fedora-sysv/chkconfig, pull requests merged in 2022-10, with the labels that each got.

#87 chkconfig: use correct cmp function
  chkconfig.c
Labels: bugfix

#84 alternatives: replace master/slave with leader/follower
  alternatives.8
  alternatives.c
  po/chkconfig.pot
  test-alternatives.sh
Labels: enhancement, RHEL9

#90 Add CodeQL to replace LGTM
  .github/workflows/codeql.yml
  README.md
Labels: ci

#92 releng: Packit remove extra job trigger
  .packit.yml
Labels: ci
