Repository fedora-sysv/chkconfig, pull requests merged in 2023-05, with the labels that each got.

#105 Translations update from Fedora Weblate
  po/ko.po
Labels: enhancement

#108 Fix way how we generate next version
  Makefile
Labels: ci

#109 Fix --keep-foreign when the target is missing completely
  alternatives.c
Labels: RHEL8

#110 Translations update from Fedora Weblate
  po/zh_CN.po
Labels: enhancement
